resolver: lts-11.1
extra-deps:
  - html-entities-1.1.4.2
  - libxml-0.1.1
  - xmlbf-0.4
  - xmlbf-xeno-0.1.1
  - git: https://github.com/dredozubov/sax-parser.git
    commit: 4eb65a8b20878311eae25a16583d4790a66400b9
